name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    uses: andreilgeorgescu/ci-devcontainter-image/.github/workflows/ci.yaml@main
    permissions:
      contents: read
      packages: write
