name: Dev Container CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # tags:
    #   - "v*.*.*"
    # pull_requests:
    #   branches:
    #     - "master"
jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        id: checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ github.repository }}
          cacheFrom: ghcr.io/${{ github.repository }}
          push: always
