name: Dev Container CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # tags:
    #   - "v*.*.*"
    # pull_requests:
    #   branches:
    #     - "master"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io
  USER_NAME: ${{ github.actor }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER_NAME }}
          password: ${{ env.PASSWORD }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.IMAGE_NAME }}
          push: always
