name: Dev Container Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          sep-tags: ","

      - name: Login to image registry
        uses: docker/login-action@v3
        env:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.actor }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER_NAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and publish image
        uses: devcontainers/ci@v0.3
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}
        with:
          subFolder: .github
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ steps.meta.outputs.tags }}
          cacheFrom: ${{ env.IMAGE_NAME }}:latest
          push: always
