name: Dev Container CI

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY: ghcr.io
  USER_NAME: ${{ github.actor }}
  MODIFIED_TAGS: "" # Initialize an environment variable for the modified tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
          sep-tags: ","

      - name: Modify and set tags
        run: echo "MODIFIED_TAGS=$(echo '${{ steps.meta.outputs.tags }}' | sed 's/${{ env.IMAGE_NAME }}://g')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USER_NAME }}
          password: ${{ env.PASSWORD }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ env.MODIFIED_TAGS }}
          cacheFrom: ${{ env.IMAGE_NAME }}:latest
          push: always
